
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: hanuairline@gmail.com
    password: 1234&Qwer
    port: 587
    protocol: smtp
    test-connection: false
    properties:
       mail:
          smtp:
             auth: true
             starttls:
                enable: true

  datasource:
    url: jdbc:mysql://hanuairline4c.mysql.database.azure.com:3306/hanuairlinedb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&zerodatetimebehavior=Converttonull
    username: hanuadmin@hanuairline4c
    password: hanu4C18
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC



  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1094375552314-cdamt79pg1sqsmfbp6p5pu57scnf6okl.apps.googleusercontent.com
            clientSecret: NkimG2EtgvcBI6FyanYpygK1
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 411945676559844
            clientSecret: 4fcf358cff68fffc18a35bd5aa0536c3
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

app:
  auth:
    tokenSecret: HanoiAirline180104
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs

paypal:
  mode: sandbox
  client:
    id: AYGF6pNoBh5rMVrDD6NGSEjzdg5aGlLxzjyhkM-rze56Dc6SuG1J1iudtVIwfE2Xiykl_ktoEdCT_gDS
    secret: EFaI-RqCEOZtiUeu3a8RYfMxkL4d18Xmgb-OD8lztZGmLWhbrJWiZImiD1ewAfj5gQOxCzptQ0RZ4xL1
